name: Generate Blog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Delete blog.html
      run: rm -f blog.html 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Run Python script
      run: python generateblog.py # Replace 'generate_html.py' with the name of your Python script
